TodoExample/Models/TodoContext.cs
using Microsoft.EntityFrameworkCore;

namespace TodoExample.Models
{
    public class TodoContext : DbContext
    {
        public DbSet<TodoItem> Todos { get; set; }
        public DbSet<Category> Categories { get; set; }

        public TodoContext(DbContextOptions<TodoContext> dbContextOptions) : 
            base(dbContextOptions)
        {
        }
    }
}

TodoExample/Models/TodoItem.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace TodoExample.Models
{
    public class TodoItem
    {
        //[Key]
        public int TodoItemId { get; set; }
        [Required(ErrorMessage = "Beschrijving mag niet leeg zijn"), 
         MinLength(2, ErrorMessage = "Lengte moet minimaal twee zin"),
         Display(Name = "Beschrijving")]
        public string Description { get; set; }

        [Required, DefaultValue(false), Display(Name = "Gedaan?")]
        public bool Done { get; set; }
        
        [Required, 
         Display(Name = "Voldaan voor"),
         DataType(DataType.Date)
        ]
        public DateTime DueDate { get; set; }


        [Display(Name = "Categorie")]
        public int CategoryId { get; set; }
        
        public Category Category { get; set; }
    }

    public class Category
    {
        public int CategoryId { get; set; }
        public string Name { get; set; }
    }
}

TodoExample/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace TodoExample.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

TodoExample/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace TodoExample.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

TodoExample/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace TodoExample.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

TodoExample/Pages/Todo/Index.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TodoExample.Models;

namespace TodoExample.Pages.Todo
{
    public class Index : PageModel
    {
        private TodoContext _db;
        public IEnumerable<TodoItem> Todos { get; set; }

        [BindProperty]
        public TodoItem AddUpdateItem { get; set; }

        [BindProperty]
        public List<SelectListItem> Categories { get; set; }

        public Index(TodoContext db)
        {
            this._db = db;
            Todos = db.Todos.Include(x => x.Category);

            Categories = db.Categories
                .Select(x => new SelectListItem(x.Name, x.CategoryId.ToString()))
                .ToList();
        }
        
        public void OnGet(string? filterCategory, bool? filterDone, string filterDescription)
        {
            if (filterDone != null)
            {
                Todos = Todos.Where(x => x.Done == filterDone);
            }

            if (!string.IsNullOrWhiteSpace(filterDescription))
            {
                Todos = Todos.Where(x => x.Description.StartsWith(filterDescription));
            }

            if (!string.IsNullOrWhiteSpace(filterCategory))
            {
                Todos = Todos.Where(x => x.Category.Name == filterCategory);
            }
        }

        public IActionResult OnPostDelete(int todoId)
        {
            TodoItem todoItemToRemove = _db.Todos.Find(todoId);
            if (todoItemToRemove == null)
            {
                return Page();
            }
            
            _db.Todos.Remove(todoItemToRemove);
            _db.SaveChanges();

            return RedirectToPage();
        }

        public IActionResult OnPostEdit(int todoId)
        {
            TodoItem todoItemToEdit = _db.Todos.Find(todoId);
            if (todoItemToEdit == null) return NotFound();

            AddUpdateItem = todoItemToEdit;
            return Page();
        }

        public IActionResult OnPostCancel()
        {
            return RedirectToPage();
        }

        public IActionResult OnPostUpdate()
        {
            if (!ModelState.IsValid)
                return Page();

            _db.Attach(AddUpdateItem).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToPage();
        }
        
        public IActionResult OnPostAdd()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            
            _db.Todos.Add(AddUpdateItem);
            _db.SaveChanges();
            
            return RedirectToPage();
        }
    }
}

TodoExample/Pages/Components/CategoryMenuComponent/Default.cshtml
@model Microsoft.EntityFrameworkCore.DbSet<TodoExample.Models.Category>

<div>
    <h1>Categories Navigation</h1>
    <ul>
        @foreach (var category in Model)
        {
            <li><a href="~/Todo/@category.Name">@category.Name</a></li>    
        }
    </ul>
</div>

TodoExample/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TodoExample/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TodoExample</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">TodoExample</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    
    <div class="container">
        @await  Component.InvokeAsync("CategoryMenuComponent")

        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - TodoExample - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

TodoExample/Pages/TestUrls.cshtml
@page "{year:int}/{month:int}/{day:int?}"
@model TodoExample.Pages.Todo.TestUrls

<h1>Test</h1>

@Request.RouteValues["year"]
<br>
@Request.RouteValues["month"]
<br>
@Request.RouteValues["day"]
<br>

TodoExample/Pages/Todo/Index.cshtml
@page "{filterCategory?}"
@using TodoExample.Models
@model TodoExample.Pages.Todo.Index

@{
    Layout = "Shared/_Layout";
@*     @functions { *@
@*         public List<Todo> Todos { get; set; } *@
@* *@
@*         public void OnGet() *@
@*         { *@
@*             Todos = new List<Todo>(); *@
@*             Random r = new Random(); *@
@*             for (int i = 0; i < r.Next(3, 10); i++) *@
@*             { *@
@*                 Todos.Add(new Todo() { Id = 1, Description = "Test", Done = r.NextDouble() >= 0.5});     *@
@*             } *@
@*         } *@
@* *@
@*         public void OnPost() *@
@*         { *@
@*             //Message = "OnPost"; *@
@*         } *@
@*     } *@
}



<h1>Todo Example!</h1>
<tooltip></tooltip>

<partial name="_TodoStats" model="Model.Todos.ToList()"/>
<ul>
    @foreach (var todo in Model.Todos)
    {
        <li>@todo.Description -- 
            @todo.Done @Html.DisplayFor(x => todo.DueDate) --
            @todo.Category.Name
            <form method="post">
                <input name="todoId" type="hidden" value="@todo.TodoItemId"/>
                <button type="submit" asp-page-handler="delete">Delete</button>
                <button type="submit" asp-page-handler="edit">Edit</button>
            </form>
        </li>    
    }
</ul>
<form method="get">
    Search: <input type="text" name="filterDescription"/><br>
    Completed: <input type="checkbox" name="filterDone" value="true"/><br>
    <button type="submit">Filter</button>
</form>

<hr><hr>

<form method="post">
    @if (Model.AddUpdateItem != null && Model.AddUpdateItem.TodoItemId != 0)
    {
        @Html.HiddenFor(x => x.AddUpdateItem.TodoItemId)
    }
    <div>
        <label asp-for="AddUpdateItem.Description"></label>
        <input asp-for="AddUpdateItem.Description"/>
        <span asp-validation-for="AddUpdateItem.Description"></span>
    </div>
    <div>
        @Html.LabelFor(x => x.AddUpdateItem.Done)
        @Html.CheckBoxFor(x => x.AddUpdateItem.Done)
        @Html.ValidationMessageFor(x => x.AddUpdateItem.Done)
        <span asp-validation-for="AddUpdateItem.Done"></span>
    </div>
    <div>
        @Html.LabelFor(x => x.AddUpdateItem.DueDate)
        <input type="date" asp-for="AddUpdateItem.DueDate"/>
        @Html.ValidationMessageFor(x => x.AddUpdateItem.DueDate)
        <span asp-validation-for="AddUpdateItem.DueDate"></span>
        
    </div>
    
    <div>
        @Html.LabelFor(x => x.AddUpdateItem.CategoryId)
        <select asp-for="AddUpdateItem.CategoryId" asp-items="@Model.Categories"></select>
    </div>
    
    
    @if (Model.AddUpdateItem == null || Model.AddUpdateItem.TodoItemId == 0)
    {
        <button type="submit" asp-page-handler="Add">Add</button>
    }
    else
    {
        <button type="submit" asp-page-handler="Update">Update</button>
    }

    <button type="submit" asp-page-handler="Cancel">Cancel</button>
</form>


@* <hr>  *@
@* <h1>With Simple Post Parameters</h1> *@
@* <form method="post" asp-page-handler="add"> *@
@*     <div> *@
@*         <label>Description</label> *@
@*         <input name="description" type="text"/> *@
@*     </div> *@
@*     <div> *@
@*         <label>Completed</label> *@
@*         <input name="done" type="checkbox"/> *@
@*     </div>     *@
@*     <button type="submit">Add</button> *@
@* </form> *@
@* *@
@* <h1>With Modelbinding</h1> *@
@* <form method="post" asp-page-handler="AddWithModelBinding"> *@
@*     <div> *@
@*         <label>Description</label> *@
@*         <input name="description" type="text"/> *@
@*     </div> *@
@*     <div> *@
@*         <label>Completed</label> *@
@*         <input name="done" value="true" type="checkbox"/> *@
@*     </div>     *@
@*     <button type="submit">Add</button>     *@
@* </form> *@

TodoExample/Pages/Todo/_TodoStats.cshtml
@model List<TodoExample.Models.TodoItem>

@{
    
}

<h1>Stats</h1>
<div>
    <p>Total: @Model.Count</p>
</div>
<div>
    <p>Not Done: @Model.Count(x => !x.Done)</p>    
</div>
<div>
    <p>Done: @Model.Count(x => x.Done)</p>
</div>

<hr/>